Completed es6-classes- Devan Rivera
devanrivera98/c0123-code-solutions pull request #100
Opened 2023-03-24 23:43 UTC by devanrivera98

<img width="598" alt="Screen Shot 2023-03-24 at 4 39 19 PM" src="https://user-images.githubusercontent.com/117954421/227662857-af004828-a121-4ee8-aefa-c30806148fe7.png">
<img width="584" alt="Screen Shot 2023-03-24 at 4 39 26 PM" src="https://user-images.githubusercontent.com/117954421/227662862-5df18c04-4c38-4e13-a4e5-e4c655a3e3aa.png">

2023-03-24 23:49 UTC, RobertGardner requested changes

2023-03-24 23:49 UTC, RobertGardner commented on es6-classes/circle.js
> +    console.log(`The radius of the Circle is ${this.radius}`);
You need to call super.print() to get the Shape's properties.
This should return a string, not log directly.

2023-03-24 23:49 UTC, RobertGardner commented on es6-classes/shape.js
> +  print() {
Return a string.

2023-03-24 23:49 UTC, RobertGardner commented on es6-classes/square.js
> +  print() {
Same as for Circle.

2023-03-25 23:26 UTC, devanrivera98 commented
<img width="1076" alt="Screen Shot 2023-03-25 at 4 17 05 PM" src="https://user-images.githubusercontent.com/117954421/227747089-fbce0d04-10da-4d0d-bf04-5548dbce7672.png">
<img width="1073" alt="Screen Shot 2023-03-25 at 4 17 10 PM" src="https://user-images.githubusercontent.com/117954421/227747093-5bba8fa4-65e5-4df2-8b84-2d600243a34b.png">

2023-03-27 17:37 UTC, RobertGardner approved these changes

2023-03-27 18:15 UTC, merged